-- DCS CIVILIAN AIR  0.1 By Burning Skies MYTH
-- Description: This script allows spawning of civilian air assets based off realtime data.


-- =====================================================================================
-- CONFIG (Editable Section)
-- =====================================================================================

local CONFIG = {
    debug = false,              -- Set to false to disable debug messages
    production_mode = false,    -- Set to true to reduce overhead and debug output

    -- Enable features
    enable_api = true,          -- Set to false to disable the civilian air system

    -- DCS file read
    api_feed_path = "C:\\YourMissionScriptFolder\\dcs_filtered_flights_caucasus.json",  -- Feed file generated by fetch_flights.py / fetch_flights_adsblol.py
    api_feed_monitor_frequency = 10,    -- How often to monitor the file for changes (seconds)

    -- Spawn limits
    maximum_spawn_limit = 60,            -- Maximum number of aircraft to spawn from the feed

    -- Aircraft defaults (the feed carries no type info, so pick a model based on origin country)
    aircraft_type = "An-26B",           -- Default DCS aircraft model used to represent feed flights
    country = country.id.UN_PEACEKEEPERS,           -- Spawning country/coalition (neutral countries such as Switzerland/UN Peacekeepers spawn as neutral units)

    -- Aircraft types available to spawn, keyed by origin country. Adds type variety beyond the
    -- default. "default" is the fallback for any country not listed here.
    aircraft_types = {
        ["default"] = "An-26B",
        ["China"]   = "C-130J-30",
        ["United States"] = "KC-135",
        ["Germany"] = "C-130J-30",
        ["Singapore"] = "C-130J-30",
    },

    -- Liveries keyed by origin country ("default" is the fallback livery_id).
    aircraft_liveries = {
        ["default"] = "Delta Air Lines",  -- default skin for C-130J-30 from any unlisted country
        ["China"]   = "Air China",        -- China-origin aircraft wear the Chinese livery
        ["Germany"] = "Luftwaffe BATS, BA 105",   -- German-origin aircraft wear the BA 105 skin
    },
    default_cruise_speed = 150,         -- Cruise speed in m/s used when feed velocity is missing

    -- Filtering
    min_altitude = 100,                 -- Minimum altitude (m) to consider a flight airborne
    ignore_callsigns = {},              -- Optional list of callsigns to never spawn (e.g. {"JSTARDB"})

    -- In-game update thresholds: reposition/re-task an already-spawned plane when its real
    -- position/direction/altitude in the feed deviates from where DCS is flying it.
    -- Tuned so corrections fire on every monitor cycle while the aircraft is off-track,
    -- rather than only once (DCS ignores repeated identical route re-tasks once aligned).
    update_position_threshold_m = 3000,     -- Horizontal distance (m) before correcting position
    update_heading_threshold_deg = 15,      -- Heading difference (deg) before correcting direction
    update_altitude_threshold_m = 100,      -- Altitude difference (m) before correcting altitude
}

-- =====================================================================================
-- DEBUG FUNCTIONS
-- =====================================================================================

--- Outputs debug messages to both DCS log and player screens.
-- @param message The debug message to display
-- @param force (optional) Force display even in production mode
-- @return void
local function debugMsg(message, force)
    env.info("[CIV-AIR] " .. message)
    if (CONFIG.debug and not CONFIG.production_mode) or force then
        trigger.action.outText(message, 10)
    end
end

--- Internal helper to display messages to specific group.
-- @param parameters Table containing groupID, ptext, pduration, pclear
-- @return void
local function showMessageForGroup(parameters)
	trigger.action.outTextForGroup(parameters.groupID, parameters.ptext, parameters.pduration, parameters.pclear)
end

--- Finds a player's group ID by their player name.
-- @param playerName The name of the player to search for
-- @return number|nil The group ID if found, nil otherwise
local function getPlayerGroupIDByName(playerName)
    if not playerName then
        return nil
    end
    
    local coalitions = {coalition.side.BLUE, coalition.side.RED, coalition.side.NEUTRAL}
    local categories = {Group.Category.AIRPLANE, Group.Category.GROUND, Group.Category.SHIP, Group.Category.HELICOPTER}
    
    for _, side in pairs(coalitions) do
        for _, category in pairs(categories) do
            local groups = coalition.getGroups(side, category)
            if groups then
                for _, group in pairs(groups) do
                    if group and group:isExist() then
                        local units = group:getUnits()
                        if units then
                            for _, unit in pairs(units) do
                                if unit and unit:isExist() then
                                    local unitPlayerName = unit:getPlayerName()
                                    if unitPlayerName == playerName then
                                        return group:getID()
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    
    return nil
end

--- Enhanced message function that can target specific players or broadcast to all.
-- @param text The message text to display
-- @param duration (optional) How long to show the message (seconds)
-- @param delaySec (optional) Delay before showing message (seconds)
-- @param clear (optional) Whether to clear existing messages
-- @param groupID (optional) Specific group ID to target
-- @param playerName (optional) Specific player name to target
-- @return void
local function setMsg(text, duration, delaySec, clear, groupID, playerName)
    
    -- If groupID is not provided, try to determine target
    if not groupID then
        if playerName then
            -- Try to find specific player's group
            groupID = getPlayerGroupIDByName(playerName)
        end
        
        -- If still no specific target, send to all players
        if not groupID then
            debugMsg("No specific player target, sending message to all players: " .. text)
            trigger.action.outText(text, duration or 10)
            return
        end
    end
    
	if clear == nil or clear == false then
        clear = false
	else
		clear = true
    end
    
    -- Use minimum delay of 0.1 seconds instead of 0 for timer reliability
    local actualDelay = math.max(delaySec or 0, 0.1)
	timer.scheduleFunction(showMessageForGroup, {groupID = groupID, ptext = text, pduration = duration or 10, pclear = clear}, timer.getTime() + actualDelay)
end

--- Broadcasts a message to all players in the mission.
-- @param text The message text to display
-- @param duration (optional) How long to show the message (seconds)
-- @param delaySec (optional) Delay before showing message (seconds)
-- @param clear (optional) Whether to clear existing messages
-- @return void
local function setMsgToAll(text, duration, delaySec, clear)
    if clear == nil or clear == false then
        clear = false
    else
        clear = true
    end
    
    local actualDelay = math.max(delaySec or 0, 0.1)
    timer.scheduleFunction(function()
        trigger.action.outText(text, duration or 10)
    end, nil, timer.getTime() + actualDelay)
end


-- =====================================================================================
-- STATE MANAGEMENT
-- =====================================================================================

local CIVAIR_STATE = {
    initialized = false,
    groupCounter = 0,
    SPAWNED_PLANES = {},        -- Track Spawned units: [callsign] = { group, unitName, spawnTime, icao24 }
    SPAWNED_HELO = {},          -- Track Spawned units: [callsign] = { group, unitName, spawnTime, icao24 }
    lastFeedMTime = nil,        -- File modification time of last processed feed
    feedTimestamp = nil,        -- Timestamp from the last processed feed (seconds since epoch)
}


-- =====================================================================================
-- CIVAIR FUNCTIONS
-- =====================================================================================


--- Counts the current number of active assets of a specific type.
-- @param assetType Type of asset to count ("plane", "helicopter")
-- @return number Current active count of the specified asset type
local function countActiveAssets(assetType)
    local count = 0
    
    if assetType == "plane" then
        for groupName, assetData in pairs(CIVAIR_STATE.SPAWNED_PLANES) do
            if assetData.group and assetData.group:isExist() then
                count = count + 1
            else
                -- Clean up dead groups
                CIVAIR_STATE.SPAWNED_PLANES[groupName] = nil
            end
        end
    else -- helos
        for groupName, assetData in pairs(CIVAIR_STATE.SPAWNED_HELO) do
            if assetData.group and assetData.group:isExist() and assetData.assetType == assetType then
                count = count + 1
            elseif not (assetData.group and assetData.group:isExist()) then
                -- Clean up dead groups
                CIVAIR_STATE.SPAWNED_HELO[groupName] = nil
            end
        end
    end
    
    return count
end


-- =====================================================================================
-- FILE READING
-- =====================================================================================

-- OpenSky state vector field indices (see https://openskynetwork.github.io/opensky-api/rest.html)
-- NOTE: OpenSky docs are 0-indexed, but Lua arrays are 1-indexed, so all values are +1
local SV_ICAO24 = 1
local SV_CALLSIGN = 2
local SV_ORIGIN_COUNTRY = 3
local SV_TIME_POSITION = 4
local SV_LAST_CONTACT = 5
local SV_LONGITUDE = 6
local SV_LATITUDE = 7
local SV_BARO_ALTITUDE = 8
local SV_ON_GROUND = 9
local SV_VELOCITY = 10
local SV_TRUE_TRACK = 11
local SV_VERTICAL_RATE = 12
local SV_SENSORS = 13
local SV_GEO_ALTITUDE = 14
local SV_SQUAWK = 15
local SV_SPI = 16
local SV_POSITION_SOURCE = 17

--- Verifies that DCS file-system access is enabled so the feed file can be read.
-- DCS must be started with the "fs" sandbox flag (io/lfs available).
-- @return boolean True if file-system access is available
local function isFileSystemEnabled()
    if io and type(io.open) == "function" then
        return true
    end
    debugMsg("ERROR: DCS file-system (fs) access is not enabled. Add the 'fs' sandbox flag so the feed file can be read.", true)
    return false
end

--- Reads the entire contents of a file from outside the mission.
-- Tries the path as-is first (absolute paths work best), then common DCS base
-- directories for relative paths, since DCS's working directory may not be
-- the folder where the feed file lives.
-- @param path Relative or absolute path to the file
-- @return string|nil File contents as a string, or nil if it could not be read
local function readExternalFile(path)
    if not isFileSystemEnabled() then
        return nil
    end

    local f = io.open(path, "r")
    if f then
        local contents = f:read("*all")
        f:close()
        return contents
    end

    debugMsg("ERROR: Could not open feed file: " .. tostring(path))
    return nil
end


-- =====================================================================================
-- JSON PARSER (recursive descent - no loadstring required)
-- =====================================================================================

local jsonPos, jsonSrc

local function jsonPeek()
    while jsonPos <= #jsonSrc do
        local c = jsonSrc:byte(jsonPos)
        if c == 32 or c == 9 or c == 10 or c == 13 then
            jsonPos = jsonPos + 1
        else
            break
        end
    end
    if jsonPos > #jsonSrc then return nil end
    return string.char(jsonSrc:byte(jsonPos))
end

local function jsonAdvance()
    jsonPos = jsonPos + 1
end

local function jsonReadString()
    jsonAdvance() -- skip opening "
    local start = jsonPos
    local parts = {}
    while jsonPos <= #jsonSrc do
        local c = jsonSrc:byte(jsonPos)
        if c == 34 then -- "
            if jsonPos > start then
                parts[#parts + 1] = jsonSrc:sub(start, jsonPos - 1)
            end
            jsonAdvance()
            return table.concat(parts)
        elseif c == 92 then -- backslash
            if jsonPos > start then
                parts[#parts + 1] = jsonSrc:sub(start, jsonPos - 1)
            end
            jsonAdvance()
            local e = string.char(jsonSrc:byte(jsonPos))
            if e == "n" then parts[#parts + 1] = "\n"
            elseif e == "r" then parts[#parts + 1] = "\r"
            elseif e == "t" then parts[#parts + 1] = "\t"
            elseif e == "b" then parts[#parts + 1] = "\b"
            elseif e == "f" then parts[#parts + 1] = "\f"
            else parts[#parts + 1] = e end
            jsonAdvance()
            start = jsonPos
        else
            jsonPos = jsonPos + 1
        end
    end
    return table.concat(parts)
end

local function jsonReadNumber()
    local start = jsonPos
    if jsonSrc:byte(jsonPos) == 45 then jsonPos = jsonPos + 1 end -- minus
    while jsonPos <= #jsonSrc and jsonSrc:byte(jsonPos) >= 48 and jsonSrc:byte(jsonPos) <= 57 do
        jsonPos = jsonPos + 1
    end
    if jsonPos <= #jsonSrc and jsonSrc:byte(jsonPos) == 46 then -- dot
        jsonPos = jsonPos + 1
        while jsonPos <= #jsonSrc and jsonSrc:byte(jsonPos) >= 48 and jsonSrc:byte(jsonPos) <= 57 do
            jsonPos = jsonPos + 1
        end
    end
    if jsonPos <= #jsonSrc and (jsonSrc:byte(jsonPos) == 101 or jsonSrc:byte(jsonPos) == 69) then -- e/E
        jsonPos = jsonPos + 1
        if jsonPos <= #jsonSrc and (jsonSrc:byte(jsonPos) == 43 or jsonSrc:byte(jsonPos) == 45) then -- +/-
            jsonPos = jsonPos + 1
        end
        while jsonPos <= #jsonSrc and jsonSrc:byte(jsonPos) >= 48 and jsonSrc:byte(jsonPos) <= 57 do
            jsonPos = jsonPos + 1
        end
    end
    return tonumber(jsonSrc:sub(start, jsonPos - 1))
end

local function jsonReadValue()
    local c = jsonPeek()
    if c == '"' then
        return jsonReadString()
    elseif c == '{' then
        jsonAdvance() -- skip {
        local obj = {}
        jsonPeek()
        if jsonSrc:byte(jsonPos) == 125 then -- }
            jsonAdvance()
            return obj
        end
        while true do
            jsonPeek()
            local key = jsonReadString()
            jsonPeek() jsonAdvance() -- skip :
            local val = jsonReadValue()
            obj[key] = val
            jsonPeek()
            if jsonSrc:byte(jsonPos) == 44 then -- ,
                jsonAdvance()
            else
                break
            end
        end
        jsonPeek() jsonAdvance() -- skip }
        return obj
    elseif c == '[' then
        jsonAdvance() -- skip [
        local arr = {}
        jsonPeek()
        if jsonSrc:byte(jsonPos) == 93 then -- ]
            jsonAdvance()
            return arr
        end
        while true do
            arr[#arr + 1] = jsonReadValue()
            jsonPeek()
            if jsonSrc:byte(jsonPos) == 44 then -- ,
                jsonAdvance()
            else
                break
            end
        end
        jsonPeek() jsonAdvance() -- skip ]
        return arr
    elseif c == 't' then
        jsonPos = jsonPos + 4
        return true
    elseif c == 'f' then
        jsonPos = jsonPos + 5
        return false
    elseif c == 'n' then
        jsonPos = jsonPos + 4
        return nil
    else
        return jsonReadNumber()
    end
end

local function jsonDecode(s)
    if not s or #s == 0 then
        debugMsg("ERROR: jsonDecode received empty input")
        return nil
    end
    jsonSrc = s
    jsonPos = 1
    local ok, result = pcall(jsonReadValue)
    if not ok then
        debugMsg("JSON parse error: " .. tostring(result))
        return nil
    end
    return result
end

--- Normalizes a callsign from the feed (strips leading/trailing whitespace).
-- @param rawCallsign Raw callsign string from the feed
-- @return string Normalized callsign, or nil if empty
local function normalizeCallsign(rawCallsign)
    if not rawCallsign then
        return nil
    end
    local callsign = rawCallsign:gsub("^%s+", ""):gsub("%s+$", "")
    if callsign == "" then
        return nil
    end
    return callsign
end

--- Converts one OpenSky state vector into a flight record usable by DCS.
-- Skips states that are on the ground, filtered out, or have no usable coordinates.
-- @param state The raw state vector array
-- @return table|nil Flight record, or nil if the state should be ignored
local function parseFlight(state)
    if type(state) ~= "table" then
        return nil
    end

    local callsign = normalizeCallsign(state[SV_CALLSIGN])
    local lat = state[SV_LATITUDE]
    local lon = state[SV_LONGITUDE]

    -- Skip flights with no callsign/coords
    if not callsign or callsign == "" or lat == nil or lon == nil then
        return nil
    end

    -- Skip flights on the ground
    if state[SV_ON_GROUND] then
        return nil
    end

    -- Altitude: prefer barometric altitude, fall back to geometric
    local altitude = state[SV_BARO_ALTITUDE] or state[SV_GEO_ALTITUDE] or 0

    -- Skip flights below the configured minimum altitude
    if altitude < CONFIG.min_altitude then
        return nil
    end

    -- Apply the ignore callsign list
    for _, ignored in ipairs(CONFIG.ignore_callsigns) do
        if callsign == ignored then
            return nil
        end
    end

    -- Velocity: fall back to the configured default cruise speed
    local speed = state[SV_VELOCITY] or CONFIG.default_cruise_speed

    -- Heading in degrees (true track from the feed)
    local headingDeg = state[SV_TRUE_TRACK] or 0

    -- Ensure altitude respects a minimum so aircraft never spawn underground
    altitude = math.max(altitude, CONFIG.min_altitude)

    return {
        icao24 = state[SV_ICAO24],
        callsign = callsign,
        origin_country = state[SV_ORIGIN_COUNTRY],
        lat = lat,
        lon = lon,
        altitude = altitude,
        speed = speed,
        headingDeg = headingDeg,
    }
end

--- Counts keys in a table.
-- @param t The table
-- @return number Number of keys
local function countTableKeys(t)
    local n = 0
    for _ in pairs(t) do
        n = n + 1
    end
    return n
end

--- Reads, parses and caches the feed file.
-- Returns a map of callsign -> flight record for all currently valid flights.
-- @return table Map of callsign -> flight record
local function readFeed()
    local flights = {}

    if not CONFIG.enable_api then
        return flights
    end

    local json = readExternalFile(CONFIG.api_feed_path)
    if not json then
        return flights
    end

    local data = jsonDecode(json)
    if type(data) ~= "table" then
        debugMsg("ERROR: Failed to parse feed file: " .. CONFIG.api_feed_path)
        return flights
    end

    -- Record when the feed data was generated (OpenSky timestamp)
    CIVAIR_STATE.feedTimestamp = data.timestamp

    local states = data.states
    if not states then
        debugMsg("ERROR: Feed file has no 'states' field")
        return flights
    end

    local parsed = 0
    for _, state in ipairs(states) do
        local flight = parseFlight(state)
        if flight then
            flights[flight.callsign] = flight
            parsed = parsed + 1
        end
    end

    debugMsg("Parsed " .. parsed .. " airborne flights from feed (call sign map size: " .. (countTableKeys(flights)) .. ")")
    return flights
end

-- =====================================================================================
-- CIVAIR FUNCTIONS
-- =====================================================================================


--- Resolves the DCS aircraft type for a flight based on its origin country.
-- Falls back to CONFIG.aircraft_type when the origin country is not mapped.
-- @param flight Flight record from parseFlight()
-- @return string DCS aircraft model name
local function resolveAircraftType(flight)
    local country = flight.origin_country
    if country and CONFIG.aircraft_types[country] then
        return CONFIG.aircraft_types[country]
    end
    return CONFIG.aircraft_type
end

--- Resolves the livery_id for a flight based on its origin country.
-- Falls back to the configured default livery when the origin country is not mapped.
-- @param flight Flight record from parseFlight()
-- @return string DCS livery id
local function resolveAircraftLivery(flight)
    local country = flight.origin_country
    if country and CONFIG.aircraft_liveries[country] then
        return CONFIG.aircraft_liveries[country]
    end
    return CONFIG.aircraft_liveries["default"] or "default"
end

--- Spawns a single civilian aircraft from a processed flight record.
-- Wrapped in pcall so a single invalid/out-of-map flight does not abort the whole feed pass.
-- @param flight Flight record from parseFlight()
-- @return boolean Success status of the spawn operation
local function spawnCIVAIRAsset(flight)
    local ok, err = pcall(function()
        -- Enforce the global spawn limit
        local currentCount = countActiveAssets("plane")
        if currentCount >= CONFIG.maximum_spawn_limit then
            debugMsg("Maximum spawn limit reached (" .. currentCount .. "/" .. CONFIG.maximum_spawn_limit .. "). Skipping " .. flight.callsign)
            return false
        end

        -- Convert geographic lat/lon to DCS local coordinates
        local point = coord.LLtoLO(flight.lat, flight.lon, flight.altitude)

        -- DCS world frame: x=north, z=east, y=up. Place a second waypoint far ahead along the
        -- feed heading so the aircraft actually flies that bearing (a single waypoint gives DCS
        -- no onward direction to follow).
        local hdgRad = math.rad(flight.headingDeg)
        local fwd = 50 * 1000 -- 50km ahead
        local wp2North = point.x + math.cos(hdgRad) * fwd
        local wp2East  = point.z + math.sin(hdgRad) * fwd

        -- Increment group counter and build names
        CIVAIR_STATE.groupCounter = CIVAIR_STATE.groupCounter + 1
        local groupName = flight.callsign
        local unitName = flight.callsign
        local groupId = math.random(1000, 9999)
        local unitId = math.random(10000, 99999)

        local groupData = {
            ["visible"] = false,
            ["tasks"] = {},
            ["uncontrollable"] = false,
            ["task"] = "Nothing",
            ["taskSelected"] = true,
            ["route"] = {
                ["points"] = {
                    [1] = {
                        ["alt"] = flight.altitude,
                        ["type"] = "Turning Point",
                        ["action"] = "Turning Point",
                        ["alt_type"] = "BARO",
                        ["speed"] = flight.speed,
                        ["y"] = point.z,
                        ["x"] = point.x,
                        ["speed_locked"] = true,
                    },
                    [2] = {
                        ["alt"] = flight.altitude,
                        ["type"] = "Turning Point",
                        ["action"] = "Turning Point",
                        ["alt_type"] = "BARO",
                        ["speed"] = flight.speed,
                        ["y"] = wp2East,
                        ["x"] = wp2North,
                        ["speed_locked"] = true,
                    },
                }
            },
            ["groupId"] = groupId,
            ["hidden"] = false,
            ["units"] = {},
            ["y"] = point.z,
            ["x"] = point.x,
            ["name"] = groupName,
            ["start_time"] = 0,
        }

        local unit = {
            ["type"] = resolveAircraftType(flight),
            ["unitId"] = unitId,
            ['callsign'] = {
                ["name"] = unitName,
                ["number"] = 15 + CIVAIR_STATE.groupCounter,
                ["modulation"] = 0,
                ["tone"] = 0
            },
            ["skill"] = "High",
            ["livery_id"] = resolveAircraftLivery(flight),
            ["onboard_num"] = string.format("%03d", 15 + CIVAIR_STATE.groupCounter),
            ["y"] = point.z,
            ["x"] = point.x,
            ["name"] = unitName,
            ["heading"] = math.rad(flight.headingDeg),
            ["speed"] = flight.speed,
            ["alt"] = flight.altitude,
            ["alt_type"] = "BARO",
            ["payload"] = {
                ["pylons"] = {},
                ["fuel"] = 60000,
                ["flare"] = 60,
                ["chaff"] = 120,
                ["gun"] = 100,
            }
        }

        groupData.units[1] = unit

        debugMsg("Spawning " .. resolveAircraftType(flight) .. " '" .. flight.callsign .. "' at LAT=" .. flight.lat .. ", LON=" .. flight.lon ..
                 " -> X=" .. math.floor(point.x) .. ", Z=" .. math.floor(point.z) .. ", alt=" .. math.floor(flight.altitude) ..
                 "m, hdg=" .. math.floor(flight.headingDeg) .. "°, spd=" .. math.floor(flight.speed) .. " m/s")

        local success, result = pcall(coalition.addGroup, CONFIG.country, Group.Category.AIRPLANE, groupData)

        if success and result then
            debugMsg("Spawned civilian aircraft: " .. groupName)
            CIVAIR_STATE.SPAWNED_PLANES[flight.callsign] = {
                group = result,
                unitName = unitName,
                spawnTime = timer.getTime(),
                icao24 = flight.icao24,
                lastFeedTimestamp = CIVAIR_STATE.feedTimestamp,
                feedLat = flight.lat,
                feedLon = flight.lon,
                feedAlt = flight.altitude,
                feedHeading = flight.headingDeg,
                feedSpeed = flight.speed,
            }
            return true
        else
            debugMsg("ERROR: Failed to spawn " .. flight.callsign .. ": " .. tostring(result))
            return false
        end
    end)

    if not ok then
        debugMsg("ERROR spawning " .. tostring(flight and flight.callsign) .. ": " .. tostring(err))
        return false
    end

    -- When pcall succeeds, its second result is the inner function's return value
    return err
end

--- Approximate horizontal distance (meters) between two lat/lon points.
-- Uses a simple equirectangular projection valid for the small feeds used here.
-- @param lat1, lon1 first point
-- @param lat2, lon2 second point
-- @return number Distance in meters
local function distanceMeters(lat1, lon1, lat2, lon2)
    local earthRadiusM = 6371000
    local dLat = math.rad(lat2 - lat1)
    local dLon = math.rad(lon2 - lon1)
    local x = dLon * math.cos(math.rad((lat1 + lat2) / 2))
    local y = dLat
    return math.sqrt(x * x + y * y) * earthRadiusM
end

--- Normalizes a heading difference to the [-180, 180] range.
-- @param a first heading in degrees
-- @param b second heading in degrees
-- @return number Signed smallest angular difference
local function headingDeltaDeg(a, b)
    local d = (a - b) % 360
    if d > 180 then d = d - 360 end
    return d
end

--- Re-tasks an already-spawned plane when its real-world position, heading or
-- altitude in the feed has deviated "wildly" from where DCS is currently flying it.
-- Rebuilds the route so the aircraft is repositioned and holds the feed altitude.
-- @param callsign the aircraft's callsign (also the group/unit name)
-- @param flight current flight record from the feed
-- @param assetData the spawned asset state entry
-- @return boolean true if an update was applied
local function updateCIVAIRAsset(callsign, flight, assetData)
    local unit = assetData.group and assetData.group:getUnit(1)
    if not unit or not unit:isExist() then
        return false
    end

    -- Current in-game position and heading of the unit
    local pos = unit:getPoint()
    if not pos then
        return false
    end
    local curLat, curLon = coord.LOtoLL(pos)
    if not curLat or not curLon then
        return false
    end
    local vel = unit:getVelocity()
    local curHdg = 0
    if vel and (math.abs(vel.x) > 0.01 or math.abs(vel.z) > 0.01) then
        -- DCS world frame: vel.x = north component, vel.z = east component.
        -- Compass heading (0=North, 90=East) = atan2(east, north) = atan2(vel.z, vel.x)
        curHdg = math.deg(math.atan2(vel.z, vel.x))
        if curHdg < 0 then curHdg = curHdg + 360 end
    end
    local curAlt = pos.y

    -- True comparison: where DCS is actually flying the plane vs where the feed says it should be.
    -- The plane legitimately moves ahead along its route between feed updates, so a generous
    -- position threshold absorbs normal forward progress; large deviations (off-track / descended)
    -- trigger a correction.
    local curDistFromFeed = distanceMeters(curLat, curLon, flight.lat, flight.lon)
    local curAltDelta = math.abs(curAlt - flight.altitude)
    local curHdgDelta = math.abs(headingDeltaDeg(curHdg, flight.headingDeg))

    local needsPos = curDistFromFeed > CONFIG.update_position_threshold_m
    local needsHdg = curHdgDelta > CONFIG.update_heading_threshold_deg
    local needsAlt = curAltDelta > CONFIG.update_altitude_threshold_m

    if not (needsPos or needsHdg or needsAlt) then
        -- Aircraft is on track and on altitude; just refresh the stored feed reference
        assetData.feedLat = flight.lat
        assetData.feedLon = flight.lon
        assetData.feedAlt = flight.altitude
        assetData.feedHeading = flight.headingDeg
        assetData.feedSpeed = flight.speed
        assetData.lastFeedTimestamp = CIVAIR_STATE.feedTimestamp
        return false
    end

    debugMsg("Updating " .. callsign ..
        " (pos " .. math.floor(curDistFromFeed) .. "m, hdg " .. math.floor(curHdgDelta) .. "deg, alt " .. math.floor(curAltDelta) ..
        "m) -> feed pos (lat " .. flight.lat .. ", lon " .. flight.lon .. ", alt " .. flight.altitude .. "m, hdg " .. flight.headingDeg .. ", spd " .. flight.speed .. ")")

    -- Rebuild a holding route at the new feed position, altitude, heading and speed
    local point = coord.LLtoLO(flight.lat, flight.lon, flight.altitude)

    -- Place the second waypoint far ahead along the feed heading so the plane cruises level.
    -- DCS world frame: x=north, z=east, so north offset = cos(heading), east offset = sin(heading).
    local hdgRad = math.rad(flight.headingDeg)
    local fwd = 50 * 1000 -- 50km ahead
    local x2 = point.x + math.cos(hdgRad) * fwd
    local z2 = point.z + math.sin(hdgRad) * fwd

    local newRoute = {
        ["points"] = {
            [1] = {
                ["alt"] = flight.altitude,
                ["type"] = "Turning Point",
                ["action"] = "Turning Point",
                ["alt_type"] = "BARO",
                ["speed"] = flight.speed,
                ["speed_locked"] = true,
                ["y"] = point.z,
                ["x"] = point.x,
            },
            [2] = {
                ["alt"] = flight.altitude,
                ["type"] = "Turning Point",
                ["action"] = "Turning Point",
                ["alt_type"] = "BARO",
                ["speed"] = flight.speed,
                ["speed_locked"] = true,
                ["y"] = z2,
                ["x"] = x2,
            },
        }
    }

    local ok, err2 = pcall(function()
        assetData.group:getController():setTask(
            { id = 'Mission', params = { route = newRoute } }
        )
    end)
    if not ok then
        debugMsg("ERROR updating task for " .. callsign .. ": " .. tostring(err2))
        return false
    end

    -- Refresh stored feed reference values
    assetData.feedLat = flight.lat
    assetData.feedLon = flight.lon
    assetData.feedAlt = flight.altitude
    assetData.feedHeading = flight.headingDeg
    assetData.feedSpeed = flight.speed
    assetData.lastFeedTimestamp = CIVAIR_STATE.feedTimestamp
    return true
end

-- =====================================================================================
-- INITIALIZATION
-- =====================================================================================

--- Removes spawned aircraft that are no longer present in the feed or no longer exist.
-- This prevents clutter from aircraft whose real-world flight has ended.
-- @param feed Map of callsign -> flight record from the current feed
-- @param fresh If false, force removal based on spawn age (garbage collection)
-- @return void
local function garbageCollectPlanes(feed, fresh)
    local now = timer.getTime()

    for callsign, assetData in pairs(CIVAIR_STATE.SPAWNED_PLANES) do
        local remove = false

        -- Removed if the group no longer exists (shot down / despawned)
        if not (assetData.group and assetData.group:isExist()) then
            remove = true
            debugMsg("GC: Removing " .. callsign .. " (group no longer exists)")
        -- Removed if its flight is no longer in the feed (flight ended / left the map)
        elseif not feed[callsign] then
            remove = true
            debugMsg("GC: Removing " .. callsign .. " (no longer in feed)")
        end

        if remove then
            if assetData.group and assetData.group:isExist() then
                assetData.group:destroy()
            end
            CIVAIR_STATE.SPAWNED_PLANES[callsign] = nil
        end
    end
end

--- Main feed processing cycle: reads the file, spawns missing aircraft, and cleans up.
-- @return void
local function processFeed()
    if not CONFIG.enable_api then
        return
    end

    -- TODO #1: Read the data from the file based off the time set in configuration
    local feed = readFeed()
    debugMsg("Feed check complete. " .. countTableKeys(feed) .. " flights, " .. countActiveAssets("plane") .. " already spawned.")

    -- TODO #2: Spawn the aircraft that are missing from the state but present in the file
    for callsign, flight in pairs(feed) do
        local assetData = CIVAIR_STATE.SPAWNED_PLANES[callsign]
        if not assetData then
            debugMsg("Spawning missing aircraft: " .. callsign)
            spawnCIVAIRAsset(flight)
        elseif assetData.group and assetData.group:isExist() then
            -- Already spawned: check for position/direction/altitude drift and correct it
            updateCIVAIRAsset(callsign, flight, assetData)
        end
    end

    -- TODO #3: Garbage collection - remove aircraft no longer in the feed
    garbageCollectPlanes(feed)

    -- Re-schedule the next feed check so the monitor loop keeps running
    timer.scheduleFunction(processFeed, nil, timer.getTime() + CONFIG.api_feed_monitor_frequency)
end

--- Initializes the CIVAIR system.
-- @return void
local function initializeCIVAIR()
    if CIVAIR_STATE.initialized then
        return
    end

    debugMsg("Initializing CIVAILIAN AIR system...")
    CIVAIR_STATE.initialized = true

    -- Abort early if DCS file-system access is not enabled (required to read the feed)
    if not isFileSystemEnabled() then
        return
    end

    debugMsg("CIVILAN AIR system initialized successfully!")

    -- processFeed() re-schedules itself, so the monitor loop continues indefinitely
    processFeed()
end

-- Initialize the system
initializeCIVAIR()